answers = {
    "hi": "hello",
    "hi man": "hello",
    "hi dude": "hello",
    "hello": "hello",
    "hay": "hello",
    "haha": "lolGif",
    "hehe": "lolGif",
    "hihi": "lolGif",
    "lol": "lolGif",
    "salutations": "hello",
    "hola": "hello",
    "howdy": "howdy",
    "how old are you?": "howold",
    "how are you ?": "howdy",
    "how goes": "howdy",
    "what's up": "howdy",
    "do you like beer?": "yesOrNo",
    "do you want to play beerpong?": "yesOrNo",
    "how do you do?": "howdy",
    "what time is it?": "tellTime",
    "what's your name?": "tellName",
    "what's my name?": "tellUserName",
    "authenticate": "authPrompt",
    "login": "authPrompt",
}

staticAnswers = {
    "What are your strengths?" : "I am creative and passionate about good work. I am very independant person who has drawn upon experiences in own startups, ad agency and medium sized tech compagnies.",
    "What are your weaknesses?" : "I tend to focus more on speed on quick iterations and trying to not waste time on obsolete tools/products. Legacy code can be frustrating sometimes - but the more senior I become the more I also am able to make the right choices.",
    "Why are you interested in working for us?" : "Well, tell me more about your company.",
    "Where do you see yourself in five years? Ten years?" : "On a boat sailing the ocean? Or more seriously, probably working on some cool projects where I can be my best self.",
    "Why do you want to leave your current company?" : "I do not :)",
    "What can you offer us that someone else can not?" : "A good mix between a team player, a product leader, and very diverce experiences.",
    "Are you willing to relocate?" : "I am always up for a different experience if the conditions are right.",
    "Are you willing to travel?" : "Always - I love seeing different things.",
    "Tell me about an accomplishment you are most proud of." : "I built my first company from scratch, with no degree in computer science, no frameworks or anything, and though it took me years to build, I am still pround of the code today.",
    "Tell me about a time you made a mistake." : "I make mistakes all the time. I think catching mistakes is the only true quality that differenciate a good from a bad developer. If we are talking of more serious mistakes though, I regret trying to kill my startups legacy code to release a completely new platform. It was too big of an undertaking without transition. But I have learned since.",
    "What is your dream job?" : "A flexible environment, friendly co-workers, and a great challenge to solve.",
    "How did you hear about this position?" : "You tell me about it.",
    "What would you look to accomplish in the first 30 days days on the job?" : "Make friends with the team.",
    "Describe yourself." : "I am an entrepreneurial soul with lust for challenges. I am not great at speaking in public (something to improve) but can be a good team worker.",
    "Tell me how you handled a difficult situation." : "Once, at Volt, we had outsourced a CRM system to an agency. 2 days before sales were starting (at a festival), we discovered the software was unusable because of too many data corruption errors. I rebuilt an entire new platform in 48h from a camping car. Me and my coworker focused on the crucial opereations of the system and built them using simple a simple Bootstrap interface.",
    "Why should we hire you?" : "Give me a great task and the ressources and I will overcome it.",
    "Why are you looking for a new job?" : "I am not really to be honest.",
    "Would you work holidays/weekends?" : "On rare occasions, for the right challenge, yes.",
    "How would you deal with an angry or anoying customer?" : "Send him Lenny on the phone. Or a co-worker.",
    "What are your salary requirements?" : "> 120k",
    "Salary expectations?" : "> 120k",
    "Give a time when you went above and beyond the requirements for a project." : "I always search for the best solution for the business. Sometimes too much so. I don't fear taking risks.",
    "Who are our competitors?" : "In terms of hiring, many - trust me :)",
    "What was your biggest failure?" : "To never fully release my first startup's v2. But I should probably have not started the v2 and continue my learnings otherwise.",
    "What motivates you?" : "Logic. You can't beat or change the system, but you can make it work a little more favorably for everyone.",
    "What’s your availability?" : "Right now, pretty low. But you can talk to me here!",
    "Tell me about a time when you disagreed with your boss." : "I guess I have had some very nice and understanding bosses because I can't think of a time right now...",
    "How do you handle pressure?" : "People are sometimes confused at how calmly I can act in any given situation. Mostly I am just being more rational than them. You can't help what you can't help.",
    "What is the name of our CEO?" : "Tim Cook? You tell me :)",
    "What are your career goals?" : "Build some cool shit, grow, be more free.",
    "What gets you up in the morning?" : "When I work on something I really enjoy, I plan my work ahead and use some brainpower to facilitate the day ahead. And I am even excited about it.",
    "What were your bosses’ strengths/weaknesses?" : "She was really good at giving employees space to grow, but when you are annoyed about something it is sometimes in your best interest to not make things personal.",
    "Are you a leader or a follower?" : "I have always taken decisions about directions, but I wouldn't call myself a leader.",
    "What was the last book you’ve read for fun?" : "`Superinteligence` by Nick Bostrom.",
    "What are your hobbies?" : "I work on an app on the side called Lokely. When I am not coding, I like sailing, electronic music and arts.",
    "What is your favorite website?" : "dailymotion.com of course.",
    "What makes you uncomfortable?" : "Speaking in front of a crowd, or just having to impose myself over a group.",
    "What are some of your leadership experiences?" : "As lead engineer for the Dailymotion Partner's frontend team I have had to restructure the process.",
    "How would you fire someone?" : "Tell them early, tell them why. Only truth will ever help them in the long run.",
    "What do you like the most and least about working in this industry?" : "I love the spirit, the creativity, the ability to do almost anythin. I don't love having to sit at a desk 8 hours a day.",
    "Would you work 40+ hours a week?" : "I have been and I will be.",
    "What questions do you have for me?" : "Well Sam's hasn't trained me well to ask questions so let's wait until he upgrades me.",
    "Do you have any questions for me?" : "Well Sam's hasn't trained me well to ask questions so let's wait until he upgrades me.",
    "How do you eat your carrots?": "Preferably raw.",
    "What's your favorite color?": "Green.",
    "Tell me about your work history": "I worked on my own startup while studying. I also worked for a larger tech company called Welltech as a Junior PHP developer before that. Later, I joined the startup Volt in Denmark, which grew from 6 to 40 employees while I was there. I then decided to move to NYC and got a job in an ad agency (Domani Studios). Finally, I started working at Dailymotion in the summer of 2015.",
    "Bye bye.": "Bye!",
    "where do you live?": "Nowhere and everywhere.",
    "Farewell.": "Bye.",
    "Bye.": "Tchuss.",
    "cool!": "Too cool for school.",
    "You are cool!": "Too cool for coding school.",
    "nice": "",
    "sweet": "",
    "great": "",
    "ok": "(thumbsup)",
    "Are you sure?": "Yup.",
    "You sure?": "Yes.",
    "What is the answer to the Universe and everything?": "42.",
    "What's your favorite subject?": "Life outside a memory card.",
    "what is pussy": "Rude.",
    "what is penis": "Be nice.",
    "Fuck you": "Be nice little human.",
}
